<?php

class videojsWidget extends CWidget
{
	/**
	 * Widget defaults options.
	 */
	public $_options = array(
		// Unique identifier, is autogenerated by default, useful for jQuery integrations.
		'id' => false,
		// video size
		'width' => 320,
		'height' => 240,
		// video file
		'video' => false,
		// show controls
		'controls' => true,
		// preload video
		'preload' => false,
		// autoplay
		'autoplay' => false,
		// loop
		'loop' => false,
		'poster' => '',
	);

	/**
	 * User options
	 */
	public $options = array();

	/**
	 * Simply publish our assets.
	 */
	public function init()
	{
        // merge options
	    $this->options = $this->options + $this->_options;

        // create id
	    if (!$this->options['id']) {
			$this->options['id'] = 'VideoJS_' . uniqid();
		}

        // publish assets
		$this->publishAssets($this->options);
	}

	/**
	 * Simply map our options to player.
	 */
	public function run()
	{
		// Start Video4All HTML
		echo "<!-- Begin VideoJS -->\n";
		echo '<video id="' . $this->options['id'] . '" class="video-js vjs-default-skin" width="' . $this->options['width'] . '" height="' . $this->options['height'] . '">' . "\n";
		echo '<source src="' . $this->options['video'] . '" type="video/mp4" />' . "\n";
		echo "</video>\n";
		echo "<!-- End VideoJS -->\n";
	}

    /**
     * Add js and css files
     */
	protected static function publishAssets($opts)
	{
		$assets = dirname(__FILE__) . '/assets';

		if (is_dir($assets)) {

		    $baseUrl = Yii::app()->assetManager->publish($assets);

            // config
		    $config = array(
		        'controls' => $opts['controls'] ? true : false,
		        'preload' => $opts['preload'] ? 'auto' : false,
		        'autoplay' => $opts['autoplay'] ? true : false,
		        'loop' => $opts['loop'] ? true : false,
		        'poster' => $opts['poster'] ? $opts['poster'] : '',
		    );

		    // Add files
			Yii::app()->clientScript->registerCoreScript('jquery');
			Yii::app()->clientScript->registerCssFile($baseUrl . '/video-js.css');
			Yii::app()->clientScript->registerScriptFile($baseUrl . '/video.js', CClientScript::POS_HEAD);

			Yii::app()->clientScript->registerScript('video.flash.js', 'videojs.options.flash.swf = "' . $baseUrl . '/video-js.swf' . '"', CClientScript::POS_HEAD);
			Yii::app()->clientScript->registerScript(
			    'video.init'. $opts['id'] .'.js',
			    'videojs("' . $opts['id'] . '", ' . json_encode($config) . ');'
			);

		} else {
			throw new Exception('EVideoJS - Error: Couldn\'t find assets to publish.');
		}
	}

}